---

- name: init installed state
  ansible.builtin.set_fact:
    minecraft_client_installed: no


- block:

    - include_tasks: debian_install.yml
      when: ansible_facts.distribution == "Debian"

    - include_tasks: linux_install.yml
      when:
        - ansible_facts.system == "Linux"
        - not minecraft_client_installed

  when: want_minecraft_client
